### ISSUE TITLE
pwpolicy_account_lockout_enforce not presenting expected result in Log

### ISSUE THREAD

**Issue by ChrisButigieg** [usnistgov/macos_security#373]
Expected Result not presenting in Log for pwpolicy_account_lockout_enforce

Output from disa-stig_xxx_baseline.log

Sat Mar  2 17:46:17 UTC 2024 pwpolicy_account_lockout_enforce failed (Result: yes

, Expected: "{'string': 'true'}") missing

**Comment by ChrisButigieg** [comment]
Worked with Eric Benfer on this today.  We are using the sonoma branch of the project.  
When running the following check, when maxFailedAttemptes=3 and minUntilFailedLoginReset=15 it produces a yes yes result
`
 /usr/bin/pwpolicy -getaccountpolicies 2> /dev/null | /usr/bin/tail +2 | /usr/bin/xmllint --xpath '//dict/key[text()="policyAttributeMaximumFailedAuthentications"]/following-sibling::integer[1]/text()' - | /usr/bin/awk '{ if ($1 <= 3) {print "yes"} else {print "no"}}'
`
Interim solution was to add | /usr/bin/sort -u to the check of the pwpolicy_account_lockout_enforce.yaml rule

**Comment by brodjieski** [comment]
It looks like the issue is if you apply both a configuration profile with the passcode settings along with applying the pwpolicy.xml file as-is from the project. This is causing duplicate entries in the password policies.

We will adjust the pwpolicy.xml file to not include those items that are set by configuration profile so that there aren't duplicates in the policy.

**Comment by robertgendler** [comment]
Merged into `sonoma`. Gonna close the issue.
