### ISSUE TITLE
audit_flags_fm_configure

### ISSUE THREAD

**Issue by robertgendler** [usnistgov/macos_security#73]
We should change fm to -fm as no 800-53 rule actually requires auditing of all file modifications (successful or not).

This will also make audit far less busy.

**Comment by robertgendler** [comment]
Updated with commit https://github.com/usnistgov/macos_security/commit/78756b826bab44395f9c36cbfa20c62f33d3ae0f

**Comment by golbiga** [comment]
merged with `main`

**Comment by cipineda** [comment]
I'm testing dev_sonoma and found that this issue is back:

The validation script is:
`/usr/bin/awk -F':' '/^flags/ { print $NF }' /etc/security/audit_control | /usr/bin/tr ',' '\n' | /usr/bin/grep -Ec '^fm'`
which returns a 0

if the `'^fm'` is changed to either `'fm'` or `'-fm'` then it returns a 1

here are the flags in my `/etc/security/audit_control' file
`flags:lo,aa,ad,-ex,-fd,-fm,-fr,-fw`

Should I open a new issue? or you follow up on this one?
